[ONEM-16570] Robot Publisher Support
LibertyGlobal/jenkins-job-wrecker pull request #31
Opened 2020-07-09 12:43 UTC by erenatas

Implementation has been done with test case.

Signed-off-by: Eren ATAS <eatas.contractor@libertyglobal.com>

2020-07-14 10:31 UTC, romanek-adam requested changes

2020-07-14 10:31 UTC, romanek-adam commented on tests/fixtures/publishers/robot.yml
> +          archive-output-xml: false
oops - the value should be inverted

2020-07-16 13:53 UTC, romanek-adam approved these changes

2020-07-20 12:17 UTC, vdanaila approved these changes

2020-07-20 12:34 UTC, merged